<?xml version="1.0"?>
<package format="3">
  <name>neural_vector_field</name>
  <version>0.0.1</version>
  <description>Neural vector field TD3 controller for 4WISD mode-switch command generation.</description>
  <maintainer email="your.email@example.com">Shuzhong Tan</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
